language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - cmake

env:
  global:
    - MAKEFLAGS=" -j 2"

before_install:
  - git submodule update --init --recursive

script:
  - ./configure
  - cd build
  - make
  - make test
