os: Visual Studio 2015

install:
  - git submodule update --init --recursive

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - ctest -C Release
